# Generated by Django 5.1.3 on 2024-11-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=12)),
                ("connection_type", models.CharField(max_length=12)),
                ("name", models.CharField(max_length=150)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
