version: '3.11'

services:
  web:
    build: ./proj
    command: sh -c "gunicorn --bind 0.0.0.0:8000 proj.proj.wsgi"
    volumes:
      - ./proj/:/usr/src/proj/
    ports:
      - 8000:8000
    env_file:
      - ./proj/.env