# Generated by Django 5.1.3 on 2024-11-26 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_slug_useraccount_user_slug_privatekey_pk_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="privatekey",
            old_name="last_call",
            new_name="last_used",
        ),
    ]
