# Generated by Django 5.1.3 on 2024-12-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_rename_last_call_privatekey_last_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatekey",
            name="status_from_api",
            field=models.CharField(default=None, max_length=3),
        ),
    ]
