# Generated by Django 5.1.3 on 2024-12-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_privatekey_status_from_api"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="privatekey",
            name="status_from_api",
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="is_organization",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="user_slug",
            field=models.SlugField(),
        ),
    ]
