# Generated by Django 5.1.3 on 2024-12-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_remove_privatekey_status_from_api_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatekey",
            name="key",
            field=models.CharField(max_length=51),
        ),
    ]
