# Generated by Django 5.1.3 on 2024-12-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_privatekey_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatekey",
            name="pk_slug",
            field=models.SlugField(),
        ),
    ]
